name: "Hello Actions"

description: "Greet someone"

author: "rabin-nyaundi@github.com"



inputs:

  MY_NAME:

    description: "Who to greet"

    required: true

    default: "Developer"



runs:

  using: "docker"

  image: "Dockerfile"



branding:

  icon: "mic"

  color: "purple"
